### ISSUE TITLE
Docker compose yml file refers to esqlate-server in gitignore

### ISSUE THREAD

**Issue by sandys** [forbesmyester/esqlate#1]
https://github.com/forbesmyester/esqlate/blob/26fb5366599cadae43d0c4d234d15823e5344c38/.gitignore

the docker-compose.yml refers to esqlate-server which is not part of the source code

**Comment by forbesmyester** [comment]
This is covered in the README ( https://github.com/forbesmyester/esqlate/blob/master/README.adoc#docker-compose-method ) - with `[ ! -d "esqlate-server" ] && git clone git@github.com:forbesmyester/esqlate-server.git esqlate-server`.

I'm against making this repository a mono repo, but I thought about making it a git link - The second and third bullet point. Might add a comment to the docker-compose to make it clear...

**Comment by forbesmyester** [comment]
Did the note, do you have any ideas on how to make this better?

**Comment by forbesmyester** [comment]
I suspect this is [genuinely confusing to users](https://news.ycombinator.com/item?id=22073373). I'm going to figure out some other way to document / implement this.

**Comment by forbesmyester** [comment]
The `docker-compose.yml` file now refers to `node_modules/esqlate-server`, which seems like a better solution as it's versioned and not necessarily bleeding edge master. I don't know if there's a better way but this solution seems to be working.

Please feel free to re-open / comment if you feel there's a better way.
