### ISSUE TITLE
docker-compose.yml file or setup steps in README.md show wrong path

### ISSUE THREAD

**Issue by z-bsod** [forbesmyester/esqlate#11]
In the Setup instuctions for setup using docker-compose you have a command to clone the esqlate-server in the subdirectory "esqlate-server".

However, the included dockerfile is expecting this to be at "./node-modules/esqlate-server" instead.

Either the docker-compose.yml file or the Readme should be modified here.

**Comment by forbesmyester** [comment]
You're right, thanks for letting me know so I could fix it :-)
